### PR TITLE
Add embed thumbnail, further error handling and custom emoji support

### PR DESCRIPTION
**Pull request by acollierr17**
This PR addresses #16 and #17:

- Add further error handling
- Add the option to set a thumbnail for the embed option
- Add proper functionality for custom emojis
- Update `README.md` to address the previous changes

### CODE REVIEW

**Comment by DamonOnYT** [comment]
@Sam-DevZ THis is a great fix to the code. However we need to test it.

**Comment by Sam-DevZ** [comment]
This is great, thanks!

**Comment by DamonOnYT** [comment]
why tf did i get an email about this?

**Comment by Sam-DevZ** [comment]
Hey! Not sure. Perhaps you commented on the PR a while ago deleted it? For some reason, you're subscribed to this thread. Sorry about that.

**Pull request merged**
