### PR TITLE
Fixed bug

### PR DESCRIPTION
**Pull request by cwchristerw**
Replaced AND (&&) to OR (||) because otherwise it will pass this stage falsely. I tested this and this will fix issue #32.

### CODE REVIEW

**Comment by acollierr17** [comment]
Hey, just leaving this comment to say I have reviewed this PR. Will test further when I'm home from vacation on Wednesday.

**Comment by cwchristerw** [comment]
Is this going anywhere :smile: I started to create own bot because I need more complex multipurpose bot, I will add this as part of it.

**Comment by cwchristerw** [comment]
If you want to this to be merged and fixed. You need to do it in few weeks because I'm going to remove this (https://github.com/cwinfo/discord-rolereact) repository.

**Comment by PlastoPyC** [comment]
Did this and the bot stopped having issues with ignoring the setupCMD.
Thanks a lot cw!

**Comment by robert-beckley** [comment]
Can confirm this fixed the issue.  Thanks @cwchristerw

**Pull request merged**
